<?php
<<<<<<< HEAD
namespace App;
=======
namespace App ;
>>>>>>> 8b45384ec0ad0ee109ea85da78c2932cbbd9ef76
use App\Serveur;

class Imprimante extends EquipementReseau {

    private string $type ;
    private bool $estCouleur ;
<<<<<<< HEAD
    public function __construct(string $typeParam, bool $estCouleurParam, string $ipParam, string $hostnameParam) {
        $this->type=$typeParam;
        $this->estCouleur=$estCouleurParam;
=======

    public function __construct(string $typeParam, bool $estCouleurParam, string $ipParam, string $hostnameParam ){
        if (!Validator::isPrinterTypeValid($typeParam)) {

            // Si l'IP est pourrie, on lance une Exception (une erreur fatale contrôlée)
            throw new \Exception("Type d’imprimante non supporté : Le type  '$typeParam' n'est pas valide !");
        }
        $this->type = $typeParam ;
        $this->estCouleur = $estCouleurParam ;
>>>>>>> 8b45384ec0ad0ee109ea85da78c2932cbbd9ef76

        parent::__construct($hostnameParam, $ipParam);

    }
<<<<<<< HEAD
    public function afficherStatut(): string
    {
        $afficherCouleur= "NON";

    if ($this->estCouleur)
        $afficherCouleur="OUI";
        return parent::afficherStatut()." | Type: ".$this->type. " | Couleur : ".$afficherCouleur ;
}
=======

    public function afficherStatut(): string
    {

        $afficheCouleur = "NON";
        if ($this->estCouleur)
            $afficheCouleur = "OUI";
        return parent::afficherStatut()."| Type : ".$this->type." | Couleur : ".$afficheCouleur  ; // TODO: Change the autogenerated stub
    }

>>>>>>> 8b45384ec0ad0ee109ea85da78c2932cbbd9ef76
}